GMAIL_USERNAME: "sethb78@gmail.com"
GMAIL_PASSWORD: "spiderricco27"
AMAZON_BUCKET_NAME: "tim_occhipinti"
AMAZON_KEY_ID: "AKIAI7X2GMZHZM22NFTA"
AMAZON_SECRET_KEY: "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"