GMAIL_USERNAME: "xxxxxxxxxxxxxx"
GMAIL_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxx"
SECRET_TOKEN:  "xxxxxxxxxxxxxxxxxxxxx"
AMAZON_BUKET_NAME: "xxxxxxxxxxxxxxxxxxxxxx"
AMAZON_KEY_ID: "xxxxxxxx"
AMAZON_SECRET_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"